### ISSUE TITLE
TensorRT部署Yolov8-出現錯誤找不到指定的模組。 (0x8007007E)' 錯誤訊息

### ISSUE THREAD

**Issue by a339708** [guojin-yan/Csharp_deploy_Yolov8#1]
已經有將TensorRTSharpExterm編譯成.dll，tensorrt_dll_path也有修改成對應路徑，但執行模型推理時，再載入model過程(Nvinfer nvinfer = new Nvinfer(model_path))，出現找不到指定的模組。 (0x8007007E)' 錯誤訊息，想詢問有相關解決辦法嗎，謝謝!!

**Comment by guojin-yan** [comment]
出现这种情况的原因是tensorRT官方库没有安装好或者没有安装，自己英伟达显卡加速驱动CUDA没有安装好，他找不到相应的依赖。可以检查检查这两个地方，TensorRT安装可以参考https://blog.csdn.net/grape_yan/article/details/127320959?app_version=5.15.4&code=app_1562916241&csdn_share_tail=%7B%22type%22%3A%22blog%22%2C%22rType%22%3A%22article%22%2C%22rId%22%3A%22127320959%22%2C%22source%22%3A%22Grape_yan%22%7D&uLinkId=usr1mkqgl919blen&utm_source=app

**Comment by a339708** [comment]
了解，另外請問有提供Egmucv或.net framework版本嗎，感謝!!

**Comment by guojin-yan** [comment]
z这个没有进行编译，你可以根据自己的需求自己进行编译
