### ISSUE TITLE
Problem with Inference at Resolutions Different from 640

### ISSUE THREAD

**Issue by OAMELLAL** [guojin-yan/Csharp_deploy_Yolov8#13]
Hello,

I'm experiencing an issue with inference when using resolutions different from 640. When training is done with a resolution of 640, the inference works fine. However, with other resolutions, it doesn't work as expected.
I've tested the inference of my models with various resolutions on Python and it works well. However, with this particular application, it doesn't work as expected. The inference is performed, but it detects many bounding boxes scattered all over.

I tested several models with resolutions of 1024 and 2560

![2024-05-21_17h28_17](https://github.com/guojin-yan/YoloDeployCsharp/assets/30500268/90d53333-562f-4e75-9a1b-bfb08d236d03)

**Comment by alanxinn** [comment]
@OAMELLAL 

Is the model input shape [1,3,1024*1024]?
If the inference image is only 1024*1024, it will be automatically resized to 640*640.
There is no need to change the value of ------input size. The default is 640, because the default yolo input is [1,3,640*640]

**Comment by OAMELLAL** [comment]
@alanxinn 

Yes the input shape  is [1,3,10241024]

![2024-05-25_20h27_34](https://github.com/guojin-yan/YoloDeployCsharp/assets/30500268/a43a7e3c-d801-4e92-b646-19d70f004698)

**Comment by alanxinn** [comment]
> @alanxinn
> 
> Yes the input shape is [1,3,10241024]
> 
> ![2024-05-25_20h27_34](https://private-user-images.githubusercontent.com/30500268/333824330-a43a7e3c-d801-4e92-b646-19d70f004698.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY2NjIyNzAsIm5iZiI6MTcxNjY2MTk3MCwicGF0aCI6Ii8zMDUwMDI2OC8zMzM4MjQzMzAtYTQzYTdlM2MtZDgwMS00ZTkyLWI2NDYtMTlkNzBmMDA0Njk4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI1VDE4MzI1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ5MjJkZjdmOTU2OTRiOGNmZTcyN2ViNGRhZGZiMjQyOTY2ZDFlNmE5YWI4MzMyMTRhZWJlZGFkZmMzNWE1ZDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7N_6m053ifEEME_3ZqfNFKfXsEXR_lCcrWWoaK1BDbg)

If there is no problem with the model, then there is a high probability that there is a problem with image pre-processing and post-processing.

**Comment by OAMELLAL** [comment]
I found the solution, you have to change 8400 by 21504 in Yolo constructor if you use 1024 resolution

**Comment by alanxinn** [comment]
model     output0 [1,84,21504]
right?

**Comment by OAMELLAL** [comment]
@alanxinn yes 21504 come from the model output
