### ISSUE TITLE
加载图片时间太长，怎么优化

### ISSUE THREAD

**Issue by scccc123** [guojin-yan/Csharp_deploy_Yolov8#8]
使用TensortRT，yolo-det进行推理，加载图片耗时300毫秒，推理时间1毫秒，如何优化代码减少加载图片的时间？

**Comment by guojin-yan** [comment]
图片处理使用的是OpenCV，其基本处理时间应该也要100多ms，其他的一些处理应该也会消耗几十ms，而其他的时间消耗主要在图片数据在C#中解码然后再C++中重构这个过程。
这一块的优化过程有两个：
第一个是采用CUDA加速OpenCV，这样可以提高图片数据处理的速度，但这个OpenCV库需要自己编译；
第二点就是对本项目封装源码的优化，目前优化思路将图片处理过程全部在C#中实现，然后将处理后的数据在传入到C++中，直接加载到推理模块上。
