### ISSUE TITLE
在更新的cuda环境中是否有可能运行？

### ISSUE THREAD

**Issue by PTA00** [guojin-yan/Csharp_deploy_Yolov8#9]
cuda_12.3.2
cudnn-windows-x86_64-8.9.0.131_cuda12-archive
TensorRT-8.6.1.6.Windows10.x86_64.cuda-12.0

如果有时间可以测试一下吗？
我这里无论如何都不可能成功，我需要对照实验。

**Comment by guojin-yan** [comment]
你好，因为我的设备与你同的环境不匹配，没有办法进行测试，你所遇到的问题可以参考一下方式进行解决：
https://github.com/guojin-yan/Csharp_deploy_Yolov8/issues/7#issuecomment-1949593554

如果问题无法解决，可以添加QQ群进行交流：945057948

**Comment by PTA00** [comment]
按照你说的方法测试成功找到问题，感谢！
